# Makefile.in generated automatically by automake 1.4-p5 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /gnome/GNOME2
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/nautilus
pkglibdir = $(libdir)/nautilus
pkgincludedir = $(includedir)/nautilus

top_builddir = ../..

ACLOCAL = aclocal -I /gnome/GNOME2/share/aclocal/gnome2-macros 
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/eazel-hacking-hacks/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = ppc-unknown-linux-gnu
host_triplet = powerpc-unknown-linux-gnu
AS = @AS@
CATALOGS =  az.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en_GB.gmo es.gmo fi.gmo fr.gmo ga.gmo gl.gmo hu.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo zh_TW.gmo
CATOBJEXT = .gmo
CC = gcc
COMPONENT_CFLAGS =    -I/gnome/GNOME2/include/eel-2 -I/gnome/GNOME2/include/gconf/2 -I/gnome/GNOME2/include/bonobo-activation-2.0 -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include -I/gnome/GNOME2/include/orbit-2.0 -I/gnome/GNOME2/include/linc-1.0 -I/gnome/GNOME2/include/libxml2 -I/gnome/GNOME2/include/gtk-2.0 -I/gnome/GNOME2/include/gnome-vfs-2.0 -I/gnome/GNOME2/lib/gnome-vfs-2.0/include -I/gnome/GNOME2/lib/gtk-2.0/include -I/gnome/GNOME2/include/pango-1.0 -I/usr/X11R6/include -I/usr/include/freetype2 -I/gnome/GNOME2/include/atk-1.0 -I/gnome/GNOME2/include/libart-2.0 -I/gnome/GNOME2/include/libgnome-2.0 -I/gnome/GNOME2/include/libbonobo-2.0 -I/gnome/GNOME2/include/libgnomecanvas-2.0 -I/gnome/GNOME2/include/libgnomeui-2.0 -I/gnome/GNOME2/include/libbonoboui-2.0 -I/gnome/GNOME2/include/gnome-vfs-module-2.0  
COMPONENT_LIBS =    -L/gnome/GNOME2/lib -L/usr/X11R6/lib -leel-2 -lgnomeui-2 -lSM -lICE -lgnome-2 -lgconf-2 -lbonoboui-2 -lbonobo-2 -lgnomecanvas-2 -lart_lgpl_2 -lpangoft2 -lgtk-x11-1.3 -lgdk-x11-1.3 -lgdk_pixbuf-1.3 -lpangox -lpangoxft -lXft -lXrender -lXext -lX11 -lfreetype -lpango -latk -lgnomevfs-2 -lbonobo-activation -lORBit-2 -llinc -lgobject-1.3 -lxml2 -lz -lm -lgthread-1.3 -lpthread -lgmodule-1.3 -ldl -lglib-1.3  
CORE_CFLAGS =       -I/gnome/GNOME2/include/eel-2 -I/gnome/GNOME2/include/gconf/2 -I/gnome/GNOME2/include/bonobo-activation-2.0 -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include -I/gnome/GNOME2/include/orbit-2.0 -I/gnome/GNOME2/include/linc-1.0 -I/gnome/GNOME2/include/libxml2 -I/gnome/GNOME2/include/gtk-2.0 -I/gnome/GNOME2/include/gnome-vfs-2.0 -I/gnome/GNOME2/lib/gnome-vfs-2.0/include -I/gnome/GNOME2/lib/gtk-2.0/include -I/gnome/GNOME2/include/pango-1.0 -I/usr/X11R6/include -I/usr/include/freetype2 -I/gnome/GNOME2/include/atk-1.0 -I/gnome/GNOME2/include/libart-2.0 -I/gnome/GNOME2/include/libgnome-2.0 -I/gnome/GNOME2/include/libbonobo-2.0 -I/gnome/GNOME2/include/libgnomecanvas-2.0 -I/gnome/GNOME2/include/libgnomeui-2.0 -I/gnome/GNOME2/include/libbonoboui-2.0 -I/gnome/GNOME2/include/librsvg-2 -I/gnome/GNOME2/include  
CORE_IDL_INCLUDES = -I /gnome/GNOME2/share/idl/bonobo-activation-2.0 -I /gnome/GNOME2/share/idl/bonobo-2.0
CORE_LIBS =       -L/gnome/GNOME2/lib -L/usr/X11R6/lib -leel-2 -lgnomeui-2 -lSM -lICE -lgnome-2 -lgnomevfs-2 -lgconf-2 -lrsvg-2 -lbonoboui-2 -lbonobo-2 -lbonobo-activation -lORBit-2 -llinc -lgthread-1.3 -lpthread -lxml2 -lz -lgnomecanvas-2 -lart_lgpl_2 -lpangoft2 -lgtk-x11-1.3 -lgdk-x11-1.3 -lgdk_pixbuf-1.3 -lpangox -lpangoxft -lXft -lXrender -lXext -lX11 -lfreetype -lpango -latk -lgobject-1.3 -lgmodule-1.3 -ldl -lglib-1.3 -lesd -laudiofile -lm     -ljpeg 
CPP = gcc -E
DATADIRNAME = share
DLLTOOL = @DLLTOOL@
ECHO = echo
EEL_REQUIRED = 1.1.2
ENABLE_PROFILER = 
EXEEXT = 
FAM_LIBS = 
GETTEXT_PACKAGE = nautilus
GIMPHWRAPBOX_CFLAGS =  -I/gnome/GNOME2/include/gtk-2.0 -I/gnome/GNOME2/lib/gtk-2.0/include -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include -I/gnome/GNOME2/include/pango-1.0 -I/usr/X11R6/include -I/usr/include/freetype2 -I/gnome/GNOME2/include/atk-1.0  
GLIB_GENMARSHAL = /gnome/GNOME2/bin/glib-genmarshal
GMOFILES =  az.gmo ca.gmo cs.gmo da.gmo de.gmo el.gmo en_GB.gmo es.gmo fi.gmo fr.gmo ga.gmo gl.gmo hu.gmo it.gmo ja.gmo ko.gmo lt.gmo lv.gmo nl.gmo nn.gmo no.gmo pl.gmo pt.gmo pt_BR.gmo ro.gmo ru.gmo sk.gmo sl.gmo sv.gmo ta.gmo tr.gmo uk.gmo zh_TW.gmo
GMSGFMT = /gnome/GNOME2/bin/msgfmt
GNOME_ACLOCAL_DIR = /gnome/GNOME2/share/aclocal/gnome2-macros
GNOME_ACLOCAL_FLAGS = -I /gnome/GNOME2/share/aclocal/gnome2-macros 
GNOME_INTERFACE_VERSION = 2
GNOME_VFS_REQUIRED = 1.1
GTKDOC = @GTKDOC@
HAVE_GTK_DOC = @HAVE_GTK_DOC@
HAVE_JW = yes
HAVE_MEDUSA = 
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
INTLTOOL_CAVES_RULE = %.caves:     %.caves.in     $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -d -u
INTLTOOL_DESKTOP_RULE = %.desktop:   %.desktop.in   $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -d -u
INTLTOOL_DIRECTORY_RULE = %.directory: %.directory.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -d -u
INTLTOOL_EXTRACT = $(top_builddir)/intltool-extract
INTLTOOL_KEYS_RULE = %.keys:      %.keys.in      $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -k -u
INTLTOOL_MERGE = $(top_builddir)/intltool-merge
INTLTOOL_OAF_RULE = %.oaf:       %.oaf.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -o -p
INTLTOOL_PERL = /usr/bin/perl
INTLTOOL_PONG_RULE = %.pong:      %.pong.in      $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -x -u
INTLTOOL_SERVER_RULE = %.server:    %.server.in    $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -o -u
INTLTOOL_SHEET_RULE = %.sheet:     %.sheet.in     $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -x -u
INTLTOOL_SOUNDLIST_RULE = %.soundlist: %.soundlist.in $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -d -u
INTLTOOL_UPDATE = $(top_builddir)/intltool-update
INTLTOOL_XML_RULE = %.xml:       %.xml.in       $(INTLTOOL_MERGE) $(wildcard $(top_srcdir)/po/*.po) ; $(INTLTOOL_MERGE) $(top_srcdir)/po $< $@ -x -u
JW = /usr/bin/jw
LIBJPEG = -ljpeg
LIBNAUTILUS_CFLAGS =     -I/gnome/GNOME2/include/eel-2 -I/gnome/GNOME2/include/gconf/2 -I/gnome/GNOME2/include/bonobo-activation-2.0 -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include -I/gnome/GNOME2/include/orbit-2.0 -I/gnome/GNOME2/include/linc-1.0 -I/gnome/GNOME2/include/libxml2 -I/gnome/GNOME2/include/gtk-2.0 -I/gnome/GNOME2/include/gnome-vfs-2.0 -I/gnome/GNOME2/lib/gnome-vfs-2.0/include -I/gnome/GNOME2/lib/gtk-2.0/include -I/gnome/GNOME2/include/pango-1.0 -I/usr/X11R6/include -I/usr/include/freetype2 -I/gnome/GNOME2/include/atk-1.0 -I/gnome/GNOME2/include/libart-2.0 -I/gnome/GNOME2/include/libgnome-2.0 -I/gnome/GNOME2/include/libbonobo-2.0 -I/gnome/GNOME2/include/libgnomecanvas-2.0 -I/gnome/GNOME2/include/libgnomeui-2.0 -I/gnome/GNOME2/include/libbonoboui-2.0  
LIBNAUTILUS_IDL_INCLUDES = -I /gnome/GNOME2/share/idl/bonobo-activation-2.0 -I /gnome/GNOME2/share/idl/bonobo-2.0
LIBNAUTILUS_LIBS =     -L/gnome/GNOME2/lib -L/usr/X11R6/lib -leel-2 -lgnomeui-2 -lSM -lICE -lgnome-2 -lgnomevfs-2 -lgconf-2 -lbonoboui-2 -lbonobo-2 -lbonobo-activation -lORBit-2 -llinc -lgthread-1.3 -lpthread -lxml2 -lz -lgnomecanvas-2 -lart_lgpl_2 -lpangoft2 -lgtk-x11-1.3 -lgdk-x11-1.3 -lgdk_pixbuf-1.3 -lm -lpangox -lpangoxft -lXft -lXrender -lXext -lX11 -lfreetype -lpango -latk -lgobject-1.3 -lgmodule-1.3 -ldl -lglib-1.3  
LIBPNG = -lpng -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = 
MAKEINFO = makeinfo
MEDUSA_REQUIRED = 0.5.1
MKINSTALLDIRS = ./mkinstalldirs
MUSIC_COMPONENT_CFLAGS =     -I/gnome/GNOME2/include/eel-2 -I/gnome/GNOME2/include/gconf/2 -I/gnome/GNOME2/include/bonobo-activation-2.0 -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include -I/gnome/GNOME2/include/orbit-2.0 -I/gnome/GNOME2/include/linc-1.0 -I/gnome/GNOME2/include/libxml2 -I/gnome/GNOME2/include/gtk-2.0 -I/gnome/GNOME2/include/gnome-vfs-2.0 -I/gnome/GNOME2/lib/gnome-vfs-2.0/include -I/gnome/GNOME2/lib/gtk-2.0/include -I/gnome/GNOME2/include/pango-1.0 -I/usr/X11R6/include -I/usr/include/freetype2 -I/gnome/GNOME2/include/atk-1.0 -I/gnome/GNOME2/include/libart-2.0 -I/gnome/GNOME2/include/libgnome-2.0 -I/gnome/GNOME2/include/libbonobo-2.0 -I/gnome/GNOME2/include/libgnomecanvas-2.0 -I/gnome/GNOME2/include/libgnomeui-2.0 -I/gnome/GNOME2/include/libbonoboui-2.0 -I/gnome/GNOME2/include/gnome-vfs-module-2.0 -I/gnome/GNOME2/include  
MUSIC_COMPONENT_LIBS =     -L/gnome/GNOME2/lib -L/usr/X11R6/lib -leel-2 -lgnomeui-2 -lSM -lICE -lgnome-2 -lgconf-2 -lbonoboui-2 -lbonobo-2 -lgnomecanvas-2 -lart_lgpl_2 -lpangoft2 -lgtk-x11-1.3 -lgdk-x11-1.3 -lgdk_pixbuf-1.3 -lpangox -lpangoxft -lXft -lXrender -lXext -lX11 -lfreetype -lpango -latk -lgnomevfs-2 -lbonobo-activation -lORBit-2 -llinc -lgobject-1.3 -lxml2 -lz -lgthread-1.3 -lpthread -lgmodule-1.3 -ldl -lglib-1.3 -lesd -laudiofile -lm  
OBJDUMP = @OBJDUMP@
OBJEXT = o
ORBIT_CFLAGS = -DORBIT2=1 -I/gnome/GNOME2/include/orbit-2.0 -I/gnome/GNOME2/include/linc-1.0 -I/gnome/GNOME2/include/glib-2.0 -I/gnome/GNOME2/lib/glib-2.0/include
ORBIT_CONFIG = /gnome/GNOME2/bin/orbit2-config
ORBIT_IDL = /gnome/GNOME2/bin/orbit-idl-2
ORBIT_LIBS = -Wl,--export-dynamic -L/gnome/GNOME2/lib -lORBit-2 -llinc -lgobject-1.3 -lgthread-1.3 -lpthread -lgmodule-1.3 -ldl -lglib-1.3 -lm
PACKAGE = nautilus
PKG_CONFIG = /gnome/GNOME2/bin/pkg-config
POFILES =  az.po ca.po cs.po da.po de.po el.po en_GB.po es.po fi.po fr.po ga.po gl.po hu.po it.po ja.po ko.po lt.po lv.po nl.po nn.po no.po pl.po pt.po pt_BR.po ro.po ru.po sk.po sl.po sv.po ta.po tr.po uk.po zh_TW.po
POSUB = po
RANLIB = ranlib
RSVG_REQUIRED = 1.1
STRIP = strip
USE_NLS = yes
VERSION = 1.1.2
XML_REQUIRED = 2.4.6

NULL = 

SUBDIRS =  	$(NULL)


icondir = $(datadir)/pixmaps/nautilus/default

icon_DATA =  	Back.png 	Forward.png 	Home.png 	Refresh.png 	Search.png 	Stop.png 	Up.png 	SearchWeb.png 	decrement.png 	default.xml 	home.png 	i-directory-12.png 	i-directory-24.png 	i-directory-36.png 	i-directory-72.png 	i-directory-96.png 	i-directory.png 	i-directory-accept-12.png 	i-directory-accept-24.png 	i-directory-accept-36.png 	i-directory-accept-72.png 	i-directory-accept-96.png 	i-directory-accept.png 	i-directory.xml 	i-directory-accept.xml 	i-regular-12.png 	i-regular-24.png 	i-regular-36.png 	i-regular-72.png 	i-regular-96.png 	i-regular.png 	i-regular.xml 	i-bookmark-20.png 	i-bookmark-missing-20.png 	i-bookmark-missing.png 	i-bookmark.png 	i-broken-image.png 	i-search-72.png 	i-spreadsheet.png 	i-stalled.png 	i-symlink.png 	i-web-72.png 	increment.png 	loading.png 	manual.png 	number_strip.png 	side_bar_image.png 	temp-home.png 	theme_preview.png 	trash-empty.png 	trash-full.png 	zoom_body.png 	$(NULL)


EXTRA_DIST = $(icon_DATA)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
DATA =  $(icon_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in:  Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu icons/default/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


install-iconDATA: $(icon_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(icondir)
	@list='$(icon_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(icondir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(icondir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(icondir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(icondir)/$$p; \
	  fi; fi; \
	done

uninstall-iconDATA:
	@$(NORMAL_UNINSTALL)
	list='$(icon_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(icondir)/$$p; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.



all-recursive install-data-recursive install-exec-recursive \
installdirs-recursive install-recursive uninstall-recursive  \
check-recursive installcheck-recursive info-recursive dvi-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	rev=''; list='$(SUBDIRS)'; for subdir in $$list; do \
	  rev="$$subdir $$rev"; \
	  test "$$subdir" != "." || dot_seen=yes; \
	done; \
	test "$$dot_seen" = "no" && rev=". $$rev"; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
   if test "$$subdir" = .; then :; else \
	    test -f $$subdir/TAGS && tags="$$tags -i $$here/$$subdir/TAGS"; \
   fi; \
	done; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = icons/default

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu icons/default/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	for subdir in $(SUBDIRS); do \
	  if test "$$subdir" = .; then :; else \
	    test -d $(distdir)/$$subdir \
	    || mkdir $(distdir)/$$subdir \
	    || exit 1; \
	    chmod 777 $(distdir)/$$subdir; \
	    (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir=../$(top_distdir) distdir=../$(distdir)/$$subdir distdir) \
	      || exit 1; \
	  fi; \
	done
info-am:
info: info-recursive
dvi-am:
dvi: dvi-recursive
check-am: all-am
check: check-recursive
installcheck-am:
installcheck: installcheck-recursive
install-exec-am:
install-exec: install-exec-recursive

install-data-am: install-iconDATA
install-data: install-data-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-recursive
uninstall-am: uninstall-iconDATA
uninstall: uninstall-recursive
all-am: Makefile $(DATA)
all-redirect: all-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs: installdirs-recursive
installdirs-am:
	$(mkinstalldirs)  $(DESTDIR)$(icondir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-recursive

clean-am:  clean-tags clean-generic mostlyclean-am

clean: clean-recursive

distclean-am:  distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-recursive

maintainer-clean-am:  maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-recursive

.PHONY: uninstall-iconDATA install-iconDATA install-data-recursive \
uninstall-data-recursive install-exec-recursive \
uninstall-exec-recursive installdirs-recursive uninstalldirs-recursive \
all-recursive check-recursive installcheck-recursive info-recursive \
dvi-recursive mostlyclean-recursive distclean-recursive clean-recursive \
maintainer-clean-recursive tags tags-recursive mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs-am \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
