#ifndef __TRILOBITE_IDL__
#define __TRILOBITE_IDL__

#include <Bonobo.idl>

module Trilobite {
	/* The basic trilobite service interface */
	interface Service : Bonobo::Unknown {
	  
		/* Should return the name of the service, eg. "TimeService" */
		string get_name ();
    
		/* Should return the version of the service, eg. "1.0" */
		string get_version ();
    
		/* Should return the company/organization who's responsible for the service, 
		   eg. "Eazel, inc."
		*/
		string get_vendor_name ();

		/* Should return URL of the company/organization who's responsible for the service, 
		   eg. "http://www.eazel.com"
		*/
		string get_vendor_url ();
    
		/* Should give a URL for the service. This should either contain 
		   a decription or a page containing account info or whatnor for the service
		*/
		string get_url ();
	  
		/* Should return a filename an icon for the service. The filename 
		   should be in a format that can be used by gnome_pixmap_file 
		 */
		string get_icon ();
	};

	/***** Root helper interfaces ******/
	
	/* The client object should define this interface to query
	   the user for the password */
	interface PasswordQueryClient : Bonobo::Unknown {
		string get_password (in string prompt);
	};

	/* The server implements this, and uses the "client" object
	   to ask for a password */
	interface PasswordQuery : Bonobo::Unknown {
		void set_query_client (in PasswordQueryClient client);
	};
};

#endif
