#undef NAUTILUS_BUILD_MESSAGE
#undef NAUTILUS_SOURCE_DIRECTORY
#undef EAZEL_BUILD_TIMESTAMP
#undef ENABLE_NLS
#undef ENABLE_PROFILER
#undef ENABLE_INSTALLER
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_MEDUSA
#undef HAVE_LIBJPEG
#undef HAVE_STPCPY
#undef HAVE_LIBBZ2
#undef HAVE_LIBFAM
#undef bzCompress
#undef bzCompressInit
#undef bzDecompress
#undef bzDecompressInit
#undef bzclose
#undef bzdopen
#undef bzerror
#undef bzflush
#undef bzopen
#undef bzread
#undef bzwrite
