/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: 8; c-basic-offset: 8 -*- */

/* 
 * Nautilus
 *
 * Copyright (C) 2000 Eazel, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/* nautilus-adapter-factory.idl - IDL for custom factory that creates
 *                     objects which wrap bonobo controls or embeddables
 *                     that are not Nautilus::Views as Nautilus::View objects.
 */

#ifndef NAUTILUS_ADAPTER_FACTORY_IDL
#define NAUTILUS_ADAPTER_FACTORY_IDL

#include <Bonobo.idl>
#include <libnautilus/nautilus-view-component.idl>

module Nautilus {

	interface ComponentAdapterFactory : Bonobo::Unknown {
		/* FIXME: should use exceptions to report reasons for failure. */
		Nautilus::View create_adapter (in Bonobo::Unknown component);
	};

};

#endif /* NAUTILUS_ADAPTER_FACTORY_IDL */
