/*
 *  This file is autogenerated from nautilus-summary-view-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Configure your service preferences");
gchar *s = N_("Go to the Eazel Services Registration Form");
gchar *s = N_("Logout from Eazel Services");
gchar *s = N_("Show the login dialog box");
gchar *s = N_("_Login to Eazel Services");
gchar *s = N_("_Logout from Eazel Services");
gchar *s = N_("_Register for Eazel Services");
gchar *s = N_("_Service Preferences");
