/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"
#include <libtrilobite/helixcode-utils.h>

extern int installer_debug;
extern int installer_test;
extern char* installer_local;

static const struct poptOption options[] = {
	{"debug", 'd', POPT_ARG_NONE, &installer_debug, 0 , N_("Show debug output"), NULL},
	{"test", 't', POPT_ARG_NONE, &installer_test, 0, N_("Test run"), NULL},
	{"local", '\0', POPT_ARG_STRING, &installer_local, 0, N_("Use local, specify xml file to yse"), NULL},
	{NULL, '\0', 0, NULL, 0}
};

int
main (int argc, char *argv[])
{
  GtkWidget *window;

#ifdef ENABLE_NLS
  bindtextdomain ("nautilus-installer", GNOMELOCALEDIR);
  textdomain ("nautilus-installer");
#endif
  gnome_init_with_popt_table ("nautilus-installer", VERSION, argc, argv, options, 0, NULL);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window = create_window ();
  set_images (window);

  gtk_widget_show (window);

  gtk_main ();
  return 0;
}

