/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"
#include <libtrilobite/helixcode-utils.h>

int
main (int argc, char *argv[])
{
  GtkWidget *window;

#ifdef ENABLE_NLS
  bindtextdomain ("nautilus-installer", GNOMELOCALEDIR);
  textdomain ("nautilus-installer");
#endif

  gnome_init ("nautilus-installer", VERSION, argc, argv);

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window = create_window ();
  set_images (window);

  if (check_for_root_user ()==FALSE) {
	  GnomeDialog *d;
	  d = GNOME_DIALOG (gnome_error_dialog_parented ("I'll bring my axe and ore and beat you...\n"
							 "This means you should run this as root", 
							 GTK_WINDOW (window)));
	  gnome_dialog_run_and_close (d);
	  return 0;
  }  

  gtk_widget_show (window);

  gtk_main ();
  return 0;
}

