[rules.property_switch_exhaustiveness]
style = "legacy"

[rules.property_canonical_name]
level = "ignore"

[rules.type_style]
level = "ignore"

[rules.include_order]
level = "ignore"

[rules.use_auto_cleanup]
level = "ignore"

[rules.g_param_spec_static_strings]
level = "ignore"

[rules.g_param_spec_null_nick_blurb]
level = "ignore"

[rules.property_enum_convention]
level = "ignore"

[rules.use_clear_functions]
level = "ignore"

[rules.g_task_source_tag]
level = "ignore"

[rules.use_g_strcmp0]
level = "ignore"

[rules.use_g_gnuc_flag_enum]
level = "ignore"

[rules.use_g_object_notify_by_pspec]
level = "ignore"

[rules.g_source_id_not_stored]
level = "ignore"
