#include <Bonobo.idl>

module Trilobite {
	module Eazel {
		interface Time : Bonobo::Unknown {

			exception NotPermitted {};

			exception CannotSet {};
			
			exception CannotGetTime {
				string url;
				string reason;
			};

			void          set_max_difference (in long maxd);
			void          set_time_url (in string url);
			unsigned long check_time () raises (CannotGetTime);
			void          update_time () raises (NotPermitted, CannotGetTime);
		};
	};
};
