/*
 *  This file is autogenerated from ./nautilus-clipboard-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_Cut Text");
gchar *s = N_("Cut the selected text to the clipboard");
gchar *s = N_("_Copy Text");
gchar *s = N_("Copy the selected text to the clipboard");
gchar *s = N_("_Paste Text");
gchar *s = N_("Paste the text stored on the clipboard");
gchar *s = N_("C_lear Text");
gchar *s = N_("Remove the selected text without putting it on the clipboard");
