/*
 *  This file is autogenerated from nautilus-sample-content-view-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Sample");
gchar *s = N_("This is a sample merged menu item");
gchar *s = N_("This is a sample merged tool bar button");
gchar *s = N_("_File");
gchar *s = N_("_Sample");
gchar *s = N_("Sample");
gchar *s = N_("This is a sample merged menu item");
gchar *s = N_("This is a sample merged tool bar button");
gchar *s = N_("_File");
gchar *s = N_("_Sample");
gchar *s = N_("Sample");
gchar *s = N_("This is a sample merged menu item");
gchar *s = N_("This is a sample merged tool bar button");
gchar *s = N_("_File");
gchar *s = N_("_Sample");
