/*
 *  This file is autogenerated from ./nautilus-sidebar-loser-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_File");
gchar *s = N_("_Kill Sidebar Loser");
gchar *s = N_("Kill the Loser sidebar panel");
gchar *s = N_("Kill Sidebar Loser");
gchar *s = N_("Kill the Loser sidebar panel");
