#include <oaf-factory.idl>
#include <Bonobo.idl>

module GNOME {
  module Desktop {
	
    interface FileOperationService {
      typedef sequence<string> FileNameList;

      typedef unsigned short XferOptions;
      const unsigned short XferOptionDefault = 0;
      const unsigned short XferOptionPreserve = 1 << 0;
      const unsigned short XferOptionFollowLinks = 1 << 1;
      const unsigned short XferOptionWithParents = 1 << 2;
      const unsigned short XferOptionRecursive = 1 << 3;
      const unsigned short XferOptionSameFS = 1 << 4;
      const unsigned short XferOptionSparseAlways = 1 << 5;
      const unsigned short XferOptionSparseNever = 1 << 6;
      const unsigned short XferOptionUpdateMode = 1 << 7;
      const unsigned short XferOptionRemoveSource = 1 << 8;

      enum XferOverwriteMode {
	XferOverwriteAbort,
	XferOverwriteQuery,
	XferOverwriteReplace,
	XferOverwriteSkip
      };

      enum XferErrorMode {
	XferErrorAbort,
	XferErrorQuery
      };

      void xfer (in string source_directory_uri,
		 in FileNameList source_file_names,
		 in string target_directory_uri,
		 in FileNameList target_file_names,
		 in XferOptions options,
		 in XferErrorMode error_mode,
		 in XferOverwriteMode overwrite_mode);
    };

  };
};
