# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.4 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..
prefix = /gnome/PR3_BRANCH
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/nautilus
pkglibdir = $(libdir)/nautilus
pkgincludedir = $(includedir)/nautilus

top_builddir = ../..

ACLOCAL = aclocal
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/eazel-hacks/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i686-pc-linux
host_triplet = i686-pc-linux-gnu
AMMONITE_CFLAGS = -I/gnome/PR3_BRANCH/include
AMMONITE_LIBS = -L/gnome/PR3_BRANCH/lib -lammonite-gtk -lammonite
APPLETS_CFLAGS = 
APPLETS_LIBS = 
AS = @AS@
BONOBOX_CFLAGS = -I/gnome/PR3_BRANCH/include -DNEED_GNOMESUPPORT_H -I/gnome/PR3_BRANCH/lib/gnome-libs/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include -I/gnome/PR3_BRANCH/include/gnome-xml
BONOBOX_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lbonobo -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgnome -lgnomesupport -lesd -laudiofile -ldb1 -lgdk_pixbuf -ltiff -ljpeg -lpng -lgtk -lgdk -lgmodule -ldl -lXext -lX11 -loaf -lORBitCosNaming -lORBit -lIIOP -lORBitutil -lglib -lnsl -lm -lbonobox -lxml -lz
BONOBO_CFLAGS = -I/gnome/PR3_BRANCH/include -DNEED_GNOMESUPPORT_H -I/gnome/PR3_BRANCH/lib/gnome-libs/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include -I/gnome/PR3_BRANCH/include/gnome-xml
BONOBO_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lbonobo -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgnome -lgnomesupport -lesd -laudiofile -ldb1 -lgdk_pixbuf -ltiff -ljpeg -lpng -lz -lgtk -lgdk -lgmodule -ldl -lXext -lX11 -loaf -lORBitCosNaming -lORBit -lIIOP -lORBitutil -lglib -lnsl -lm
BONOBO_PRINT_CFLAGS = 
BONOBO_PRINT_LIBS = 
CATALOGS = 
CATOBJEXT = .gmo
CC = gcc
CPP = gcc -E
CXX = g++
DATADIRNAME = share
DLLTOOL = @DLLTOOL@
EAZEL_SERVICES = 1
ENABLE_PROFILER = 
ESD_CFLAGS = -I/gnome/PR3_BRANCH/include
ESD_CONFIG = /gnome/PR3_BRANCH/bin/esd-config
ESD_LIBS = -L/gnome/PR3_BRANCH/lib -lesd -laudiofile -lm
FREETYPE2_CFLAGS = -I/usr/include/freetype2
FREETYPE2_LIBS = -L/usr/lib -lfreetype
GCONF_CFLAGS = -I/gnome/PR3_BRANCH/include/gconf/1 -I/gnome/PR3_BRANCH/include -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/usr/X11R6/include
GCONF_CONFIG = /gnome/PR3_BRANCH/bin/gconf-config
GCONF_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lgconf-gtk-1 -lgconf-1 -loaf -lORBitCosNaming -lORBit -lIIOP -lORBitutil -lnsl -lgtk -lgdk -lgmodule -lglib -ldl -lXext -lX11 -lm
GDK_PIXBUF_CFLAGS = -I/gnome/PR3_BRANCH/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include
GDK_PIXBUF_CONFIG = /gnome/PR3_BRANCH/bin/gdk-pixbuf-config
GDK_PIXBUF_LIBS = -L/gnome/PR3_BRANCH/lib -lgdk_pixbuf -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXext -lX11 -lm
GENCAT = 
GHTTP_CFLAGS = -I/gnome/PR3_BRANCH/include
GHTTP_LIBS = -L/gnome/PR3_BRANCH/lib -lghttp
GLIB_CFLAGS = -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include
GLIB_CONFIG = /gnome/PR3_BRANCH/bin/glib-config
GLIB_LIBS = -L/gnome/PR3_BRANCH/lib -lglib
GMOFILES =  ca.gmo da.gmo de.gmo en_GB.gmo es.gmo fi.gmo fr.gmo ga.gmo gl.gmo hu.gmo it.gmo ja.gmo ko.gmo nl.gmo no.gmo pl.gmo pt_BR.gmo ru.gmo sk.gmo sv.gmo ta.gmo tr.gmo uk.gmo zh_TW.Big5.gmo
GMSGFMT = /gnome/PR3_BRANCH/bin/msgfmt
GNOMECANVASPIXBUF_INCLUDEDIR = 
GNOMECANVASPIXBUF_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lgdk_pixbuf -ltiff -ljpeg -lpng -lz -lgtk -lgdk -lgmodule -lglib -ldl -lXext -lX11 -lm -lgnomecanvaspixbuf
GNOMEUI_CFLAGS = -I/gnome/PR3_BRANCH/include -DNEED_GNOMESUPPORT_H -I/gnome/PR3_BRANCH/lib/gnome-libs/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include
GNOMEUI_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lgnomeui -lart_lgpl -lgdk_imlib -lSM -lICE -lgtk -lgdk -lgmodule -lXext -lX11 -lgnome -lgnomesupport -lesd -laudiofile -lm -ldb1 -lglib -ldl
GNOME_CFLAGS = -I/gnome/PR3_BRANCH/include -DNEED_GNOMESUPPORT_H -I/gnome/PR3_BRANCH/lib/gnome-libs/include -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include
GNOME_CONFIG = /gnome/PR3_BRANCH/bin/gnome-config
GNOME_LIBS = -L/gnome/PR3_BRANCH/lib -lgnome -lgnomesupport -lesd -laudiofile -lm -ldb1 -lglib -ldl
GNORBA_CFLAGS = 
GNORBA_LIBS = 
GTK_CFLAGS = -I/gnome/PR3_BRANCH/include/gtk-1.2 -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/usr/X11R6/include
GTK_CONFIG = /gnome/PR3_BRANCH/bin/gtk-config
GTK_LIBS = -L/gnome/PR3_BRANCH/lib -L/usr/X11R6/lib -lgtk -lgdk -rdynamic -lgmodule -lglib -ldl -lXext -lX11 -lm
GT_NO = 
GT_YES = #YES#
HAVE_APPLETS = no
IDL_CFLAGS = -I/gnome/PR3_BRANCH/share/idl -I$(top_srcdir) -I$(top_builddir)
INCLUDE_LOCALE_H = #include <locale.h>
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LIBPNG = -lpng -lz
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = makeinfo
MEDUSA_CFLAGS = -I/gnome/PR3_BRANCH/include -I/gnome/PR3_BRANCH/lib/vfs/include -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -D_REENTRANT -Wsign-promo -Wno-sign-compare
MEDUSA_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -lmedusa -lgnomevfs -lgmodule -lgthread -lglib -lpthread -ldl
MKINSTALLDIRS = ./mkinstalldirs
MOZILLA_COMPONENT_CFLAGS = -I/usr/include/mozilla -fno-rtti -fno-exceptions
MOZILLA_COMPONENT_DEBUG_FLAGS = 
MOZILLA_COMPONENT_LDFLAGS = -L/usr/lib/mozilla
MOZILLA_COMPONENT_LIBS = -lgtkembedmoz 				-lgtksuperwin 				-lxpcom 				-lnspr4 				-lplc4 				-lplds4
MOZILLA_COMPONENT_RPATH_FLAGS = -Wl,-rpath=/usr/lib/mozilla
MOZILLA_MILESTONE = 18
OAF_CFLAGS = -I/gnome/PR3_BRANCH/include -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include
OAF_CONFIG = /gnome/PR3_BRANCH/bin/oaf-config
OAF_LIBS = -L/gnome/PR3_BRANCH/lib -loaf -lORBitCosNaming -lORBit -lIIOP -lORBitutil -lglib -lnsl -lm
OBJDUMP = @OBJDUMP@
ORBIT_CFLAGS = -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -I/gnome/PR3_BRANCH/include
ORBIT_CONFIG = /gnome/PR3_BRANCH/bin/orbit-config
ORBIT_IDL = /gnome/PR3_BRANCH/bin/orbit-idl
ORBIT_LIBS = -L/gnome/PR3_BRANCH/lib -lORBit -lIIOP -lORBitutil -lglib -lnsl -lm
PACKAGE = nautilus
PACKAGESYSTEM = libeazelpackagesystem-rpm3.la
PAM_LIBS = -ldl -lpam -lpam_misc
POFILES =  ca.po da.po de.po en_GB.po es.po fi.po fr.po ga.po gl.po hu.po it.po ja.po ko.po nl.po no.po pl.po pt_BR.po ru.po sk.po sv.po ta.po tr.po uk.po zh_TW.Big5.po
POSUB = po
RANLIB = ranlib
RPM_LIBS = -lrpm -lz -lbz2 -lpopt -ldb1
RPM_VERSION = 3.0.5
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 0.8
VFS_CFLAGS = -I/gnome/PR3_BRANCH/include -I/gnome/PR3_BRANCH/lib/vfs/include -I/gnome/PR3_BRANCH/include/glib-1.2 -I/gnome/PR3_BRANCH/lib/glib/include -D_REENTRANT -Wsign-promo -Wno-sign-compare
VFS_LIBS = -rdynamic -L/gnome/PR3_BRANCH/lib -lgnomevfs -lgmodule -lgthread -lglib -lpthread -ldl
XML_CFLAGS = -I/gnome/PR3_BRANCH/include/gnome-xml
XML_CONFIG = /gnome/PR3_BRANCH/bin/xml-config
XML_I18N_EXTRACT = $(top_srcdir)/xml-i18n-extract
XML_I18N_MERGE = $(top_srcdir)/xml-i18n-merge
XML_I18N_UPDATE = $(top_srcdir)/xml-i18n-update
XML_LIBS = -L/gnome/PR3_BRANCH/lib -lxml -lz
ZVT_LIBS = 
Z_LIBS = -lz
gnomelocaledir = ${prefix}/${DATADIRNAME}/locale
l = 

crux_eggplantdir = $(datadir)/pixmaps/nautilus/crux_eggplant

SUBDIRS = sidebar_tab_pieces backgrounds throbber

crux_eggplant_DATA =  	crux_eggplant.xml			Back.png		Forward.png		Up.png		Refresh.png		Home.png		Search.png		SearchWeb.png		Stop.png		decrement.png			decrement-i.png			emblem-nowrite.png		emblem-nowrite-72.png      	emblem-nowrite-96.png		i-directory-aa.png		i-directory-72-aa.png		i-directory-96-aa.png		i-directory-192-aa.png		i-directory.png			i-directory-72.png		i-directory.xml			i-regular-72-aa.png		i-regular-96-aa.png		i-regular-192-aa.png		i-regular-aa.png		i-regular-72.png		i-regular-96.png		i-regular-192.png		i-regular.png		i-regular.xml			increment.png			increment-i.png			number_strip.png		theme_preview.png		zoom_body.png


EXTRA_DIST = $(crux_eggplant_DATA)
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
DATA =  $(crux_eggplant_DATA)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = gtar
GZIP_ENV = --best
all: all-redirect
.SUFFIXES:
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu icons/crux_eggplant/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


install-crux_eggplantDATA: $(crux_eggplant_DATA)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(crux_eggplantdir)
	@list='$(crux_eggplant_DATA)'; for p in $$list; do \
	  if test -f $(srcdir)/$$p; then \
	    echo " $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(crux_eggplantdir)/$$p"; \
	    $(INSTALL_DATA) $(srcdir)/$$p $(DESTDIR)$(crux_eggplantdir)/$$p; \
	  else if test -f $$p; then \
	    echo " $(INSTALL_DATA) $$p $(DESTDIR)$(crux_eggplantdir)/$$p"; \
	    $(INSTALL_DATA) $$p $(DESTDIR)$(crux_eggplantdir)/$$p; \
	  fi; fi; \
	done

uninstall-crux_eggplantDATA:
	@$(NORMAL_UNINSTALL)
	list='$(crux_eggplant_DATA)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(crux_eggplantdir)/$$p; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.



all-recursive install-data-recursive install-exec-recursive \
installdirs-recursive install-recursive uninstall-recursive  \
check-recursive installcheck-recursive info-recursive dvi-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@set fnord $(MAKEFLAGS); amf=$$2; \
	dot_seen=no; \
	rev=''; list='$(SUBDIRS)'; for subdir in $$list; do \
	  rev="$$subdir $$rev"; \
	  test "$$subdir" = "." && dot_seen=yes; \
	done; \
	test "$$dot_seen" = "no" && rev=". $$rev"; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	   || case "$$amf" in *=*) exit 1;; *k*) fail=yes;; *) exit 1;; esac; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS: tags-recursive $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
   if test "$$subdir" = .; then :; else \
	    test -f $$subdir/TAGS && tags="$$tags -i $$here/$$subdir/TAGS"; \
   fi; \
	done; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags $(ETAGS_ARGS) $$tags  $$unique $(LISP) -o $$here/TAGS)

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = icons/crux_eggplant

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu icons/crux_eggplant/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done
	for subdir in $(SUBDIRS); do \
	  if test "$$subdir" = .; then :; else \
	    test -d $(distdir)/$$subdir \
	    || mkdir $(distdir)/$$subdir \
	    || exit 1; \
	    chmod 777 $(distdir)/$$subdir; \
	    (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) top_distdir=../$(top_distdir) distdir=../$(distdir)/$$subdir distdir) \
	      || exit 1; \
	  fi; \
	done
info-am:
info: info-recursive
dvi-am:
dvi: dvi-recursive
check-am: all-am
check: check-recursive
installcheck-am:
installcheck: installcheck-recursive
install-exec-am:
install-exec: install-exec-recursive

install-data-am: install-crux_eggplantDATA
install-data: install-data-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-recursive
uninstall-am: uninstall-crux_eggplantDATA
uninstall: uninstall-recursive
all-am: Makefile $(DATA)
all-redirect: all-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs: installdirs-recursive
installdirs-am:
	$(mkinstalldirs)  $(DESTDIR)$(crux_eggplantdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-recursive

clean-am:  clean-tags clean-generic mostlyclean-am

clean: clean-recursive

distclean-am:  distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-recursive

maintainer-clean-am:  maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-recursive

.PHONY: uninstall-crux_eggplantDATA install-crux_eggplantDATA \
install-data-recursive uninstall-data-recursive install-exec-recursive \
uninstall-exec-recursive installdirs-recursive uninstalldirs-recursive \
all-recursive check-recursive installcheck-recursive info-recursive \
dvi-recursive mostlyclean-recursive distclean-recursive clean-recursive \
maintainer-clean-recursive tags tags-recursive mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs-am \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
