/*
 *  This file is autogenerated from ./nautilus-search-list-view-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_Reveal in New Window");
gchar *s = N_("Reveal each selected item in its original folder");
gchar *s = N_("Show _Indexing Status");
gchar *s = N_("Show status of indexing used by searching");
