/*
 *  This file is autogenerated from ./nautilus-icon-view-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("_Rename");
gchar *s = N_("Rename selected icon");
gchar *s = N_("_Icon Captions...");
gchar *s = N_("Choose which information appears beneath each icon's name");
gchar *s = N_("_Stretch Icon");
gchar *s = N_("Make the selected icon stretchable");
gchar *s = N_("_Restore Icons' Original Sizes");
gchar *s = N_("Restore each selected icon to its original size");
gchar *s = N_("_Lay out items");
gchar *s = N_("_manually");
gchar *s = N_("Leave icons wherever they are dropped");
gchar *s = N_("by _Name");
gchar *s = N_("Keep icons sorted by name in rows");
gchar *s = N_("by _Size");
gchar *s = N_("Keep icons sorted by size in rows");
gchar *s = N_("by _Type");
gchar *s = N_("Keep icons sorted by type in rows");
gchar *s = N_("by Modification _Date");
gchar *s = N_("Keep icons sorted by modification date in rows");
gchar *s = N_("by _Emblems");
gchar *s = N_("Keep icons sorted by emblems in rows");
gchar *s = N_("_Tighter Layout");
gchar *s = N_("Toggle using a tighter layout scheme");
gchar *s = N_("Re_versed Order");
gchar *s = N_("Display icons in the opposite order");
gchar *s = N_("_Clean Up by Name");
gchar *s = N_("Reposition icons to better fit in the window and avoid overlapping");
