/*
 *  This file is autogenerated from nautilus-directory-view-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Choose another application with which to open the selected item");
gchar *s = N_("Choose another viewer with which to view the selected item");
gchar *s = N_("Create _Link");
gchar *s = N_("Create a new empty folder inside this folder");
gchar *s = N_("Create a symbolic link for each selected item");
gchar *s = N_("Delete all items in the trash");
gchar *s = N_("Duplicate each selected item");
gchar *s = N_("Move each selected item to the Trash");
gchar *s = N_("Move to _Trash");
gchar *s = N_("New Folder");
gchar *s = N_("Open With");
gchar *s = N_("Open each selected item in a new window");
gchar *s = N_("Open the selected item in this window");
gchar *s = N_("Other _Application...");
gchar *s = N_("Other _Viewer...");
gchar *s = N_("R_emove Custom Images");
gchar *s = N_("Remove any custom images from selected icons");
gchar *s = N_("Select all items in this window");
gchar *s = N_("Show _Properties");
gchar *s = N_("View or modify the properties of each selected item");
gchar *s = N_("_Duplicate");
gchar *s = N_("_Empty Trash");
gchar *s = N_("_Open");
gchar *s = N_("_Open in New Window");
gchar *s = N_("_Select All Files");
gchar *s = N_("Choose another application with which to open the selected item");
gchar *s = N_("Choose another viewer with which to view the selected item");
gchar *s = N_("Create _Link");
gchar *s = N_("Create a new empty folder inside this folder");
gchar *s = N_("Create a symbolic link for each selected item");
gchar *s = N_("Delete all items in the trash");
gchar *s = N_("Duplicate each selected item");
gchar *s = N_("Move each selected item to the Trash");
gchar *s = N_("Move to _Trash");
gchar *s = N_("New Folder");
gchar *s = N_("Open With");
gchar *s = N_("Open each selected item in a new window");
gchar *s = N_("Open the selected item in this window");
gchar *s = N_("Other _Application...");
gchar *s = N_("Other _Viewer...");
gchar *s = N_("R_emove Custom Images");
gchar *s = N_("Remove any custom images from selected icons");
gchar *s = N_("Select all items in this window");
gchar *s = N_("Show _Properties");
gchar *s = N_("View or modify the properties of each selected item");
gchar *s = N_("_Duplicate");
gchar *s = N_("_Empty Trash");
gchar *s = N_("_Open");
gchar *s = N_("_Open in New Window");
gchar *s = N_("_Select All Files");
