CC=gcc
CFLAGS=`gnome-config gnomeui --cflags` -g -Wall  `xml-config --cflags`
LIBS=`gnome-config gnomeui --libs`  `xml-config --libs`

OBJS=	\
	gdb3html.o toc-elements.o sect-elements.o sect-preparse.o

all: gnome-db2html2

clean: 
	rm -f *o gnome-db2html2 core

gnome-db2html2: $(OBJS) 
	gcc -o gnome-db2html2 $(OBJS) $(LIBS)

