.TH nautilus-autorun-software 1 "3 July 2019"

.SH NAME
Run Software \- helper tool

.SH SYNOPSIS
.B nautilus-autorun-software
.RI "" "mount-uri"
.br

.SH DESCRIPTION
.B nautilus-autorun-software
is a helper tool for the GNOME desktop to start software from media with
Autostart files.
.br

It is the default "x-content/unix-software" handler for the GNOME desktop.
.br

.SH SEE ALSO
Autostart files are described at
https://specifications.freedesktop.org/autostart-spec/autostart-spec-latest.html

.SH BUGS
Bug reports can be found and filed at
https://gitlab.gnome.org/GNOME/nautilus/issues
