/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: 8; c-basic-offset: 8 -*- */

#ifndef NAUTILUS_SHELL_INTERFACE_IDL
#define NAUTILUS_SHELL_INTERFACE_IDL

#include <Bonobo.idl>
#include <libnautilus/nautilus-view-component.idl>

module Nautilus {

	interface Shell : ::Bonobo::Unknown {
		void open_windows (in URIList uris, in string geometry);
		void open_default_window (in string geometry);
		void start_desktop ();
		void stop_desktop ();
		void quit ();
		void restart ();
	};

};

#endif /* NAUTILUS_SHELL_INTERFACE_IDL */
