/*
 *  This file is autogenerated from nautilus-service-ui.xml, do not edit
 *
 *  This file contains translatable strings generated by
 * bonobo-ui-extract. Add this file to your project's
 * POTFILES.in. DO NOT compile it as part of your application.
 */

gchar *s = N_("Display support information for Eazel Services");
gchar *s = N_("Go to the Eazel Services Summary Page");
gchar *s = N_("Go to the Eazel Software Catalog");
gchar *s = N_("Go to your online storage repository");
gchar *s = N_("Services");
gchar *s = N_("Software _Catalog");
gchar *s = N_("_Eazel Services Home");
gchar *s = N_("_Online Storage");
gchar *s = N_("_Services");
gchar *s = N_("_Support");
gchar *s = N_("Display support information for Eazel Services");
gchar *s = N_("Go to the Eazel Services Summary Page");
gchar *s = N_("Go to the Eazel Software Catalog");
gchar *s = N_("Go to your online storage repository");
gchar *s = N_("Services");
gchar *s = N_("Software _Catalog");
gchar *s = N_("_Eazel Services Home");
gchar *s = N_("_Online Storage");
gchar *s = N_("_Services");
gchar *s = N_("_Support");
