#!/bin/sh

##
## Disable the gnome crash dialog.  Once bug buddy supports 
## Bugzilla, we will turn take this hack out.
##
GNOME_DISABLE_CRASH_DIALOG=1 ; export GNOME_DISABLE_CRASH_DIALOG

##
## Find out if Nautilus is already running
##
ps ax|awk '{ print $5; }' | grep -w -e  "nautilus$" > /dev/null 2>&1

ps_rv=$?

if [ $ps_rv -eq 1 ]
then
  ##
  ## Start with a fresh environment
  ##
  nautilus-clean.sh -q -x

  ##
  ## Run Nautilus with optional command line arguments.
  ## This should open the first Nautilus window.
  ##
  nautilus ${1+"$@"}
  RETURN=$?

  ##
  ## End with a fresh environment
  ##
  nautilus-clean.sh -q -x
else
  ##
  ## Run Nautilus with optional command line arguments
  ## This should open a new window on the currently running Nautilus
  nautilus ${1+"$@"}
  RETURN=$?
fi

exit $RETURN
