/* -*- Mode: IDL; tab-width: 8; indent-tabs-mode: 8; c-basic-offset: 8 -*- */

#include <Bonobo.idl>

module Trilobite {
	module Eazel {
		interface InventoryUploadCallback : Bonobo::Unknown {
			/* FIXME: need to report more specific error on failure */
			oneway void done_uploading (in boolean succeeded);
		};

		interface Inventory : Bonobo::Unknown {
			attribute boolean enabled;
			readonly attribute string machine_id;

			/* Will not actually upload if inventory is
			 * unchanged since last upload, or if
			 * inventory is not enabled.
			 */

			oneway void upload (in InventoryUploadCallback listener);
		};
	};
};

